[platformio]
default_envs = zectrix_note4

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  bblanchon/ArduinoJson@6.21.6
  adafruit/Adafruit GFX Library@1.12.6
  adafruit/Adafruit BusIO@1.17.4
  ricmoo/QRCode@0.0.1
check_skip_packages = yes
check_flags =
  cppcheck: --suppress=legacyUninitvar:*/ArduinoJson/*/ConverterImpl.hpp

[env:zectrix_note4]
board = esp32-s3-devkitc-1
upload_speed = 921600
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags =
  ${env.build_flags}
  -DTRANSITINK_BOARD_ZECTRIX_NOTE4=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM

[env:button_mapper]
extends = env:zectrix_note4
build_flags =
  ${env:zectrix_note4.build_flags}
  -D BUTTON_MAPPER
