#pragma once

#define FIRMWARE_PRODUCT_NAME "TransitInk OS"
#define FIRMWARE_SHORT_NAME "TransitInk"
#define FIRMWARE_PRODUCT_ID "transitink-os"
#define FIRMWARE_BOARD_ID "zectrix_note4"
#define DEVICE_NAME FIRMWARE_PRODUCT_NAME
#define FIRMWARE_VERSION "1.2.1"
#define CONFIG_AP_PREFIX FIRMWARE_SHORT_NAME

#ifndef TRANSITINK_FIRMWARE_UPDATE_BASE_URL
#define TRANSITINK_FIRMWARE_UPDATE_BASE_URL \
    "https://zerie55699.github.io/transitink-os"
#endif

#define ETA_REFRESH_DEFAULT_SECONDS 45
#define ETA_MAX_ROUTES 4
#define WIDGET_PAGE_CACHE_TTL_SECONDS 180
#define WEATHER_REFRESH_SECONDS 900
#define COMMUTE_DASHBOARD_ENABLED 1
#define COMMUTE_AUTOMATIC_START_MINUTES 360
#define COMMUTE_RAPID_POLL_START_MINUTES 400
#define COMMUTE_RECOVERY_START_MINUTES 430
#define COMMUTE_AUTOMATIC_END_MINUTES 450
#define COMMUTE_NORMAL_POLL_SECONDS 120
#define COMMUTE_RAPID_POLL_SECONDS 30
#define COMMUTE_RECOVERY_POLL_SECONDS 120
#define COMMUTE_MANUAL_POLL_SECONDS 30
#define COMMUTE_MANUAL_SESSION_MINUTES 10
#define COMMUTE_WEATHER_REFRESH_SECONDS 900
#define COMMUTE_FORECAST_REFRESH_SECONDS 1800
#define COMMUTE_POWER_TELEMETRY_SECONDS 900
#define COMMUTE_TIME_SYNC_RETRY_SECONDS 300
#define COMMUTE_JOINT_ETA_DEDUP_SECONDS 90
#define COMMUTE_TARGET_HOUR 7
#define COMMUTE_TARGET_MINUTE 25
#define COMMUTE_ROUTE_A_WALK_MINUTES 4
#define COMMUTE_ROUTE_B_WALK_MINUTES 13
#define COMMUTE_BOARDING_BUFFER_MINUTES 2
#define COMMUTE_TRANSFER_BUFFER_MINUTES 2
// Conservative segment estimates derived from the official route geometry and
// published whole-route journey times; live ETA rows are never used as a proxy
// for time spent travelling between stops.
#define COMMUTE_106_RIDE_MINUTES 17
#define COMMUTE_8P_RIDE_MINUTES 27
#define COMMUTE_118_RIDE_MINUTES 35
#define COMMUTE_SAFE_ARRIVAL_MARGIN_MINUTES 5
#define COMMUTE_MAXIMUM_ETA_AGE_MINUTES 3
#define SLEEP_ENABLED_DEFAULT 1
#define SLEEP_WAKE_DEFAULT_MINUTES 5
#define SLEEP_MAINTENANCE_DEFAULT_HOURS 12
#define SCHEDULED_WAKE_ENABLED_DEFAULT 1
#define SCHEDULED_WAKE_START_DEFAULT_MINUTES COMMUTE_AUTOMATIC_START_MINUTES
#define SCHEDULED_WAKE_END_DEFAULT_MINUTES COMMUTE_AUTOMATIC_END_MINUTES
